# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import emails.submodels.email


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_email_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='email',
            name='verification_hash',
            field=models.CharField(default=emails.submodels.email.create_hash, max_length=32, unique=True),
        ),
    ]
