# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_emailsenderlogger_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsenderlogger',
            old_name='result',
            new_name='error',
        ),
    ]
