# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20180622_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsenderlogger',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'success'), ('FAILURE', 'failure')], max_length=255),
        ),
    ]
